# Generated by Django 4.1 on 2022-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedsong',
            name='author',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
