# Generated by Django 4.1 on 2022-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadedsong_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedsong',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
